services:
  streamsim:
    image: streamsim
    command: python stream_simulator/bin/main.py "${UID:-123}"
    network_mode: host
    environment:
      - BROKER_HOST=locsys.issel.ee.auth.gr
      - BROKER_PORT=1883
      - BROKER_USERNAME=guest
      - BROKER_PASSWORD=guest
      - USE_REDIS=true
      - UID=123
