name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis-version: [7]

    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Start Redis
      uses: supercharge/redis-github-action@1.7.0
      with:
        redis-version: ${{ matrix.redis-version }}

    - name: Create .env file
      run: |
        echo "USE_REDIS=${{ secrets.USE_REDIS }}" > .env
        echo "BROKER_HOST=${{ secrets.BROKER_HOST }}" >> .env
        echo "BROKER_PORT=${{ secrets.BROKER_PORT }}" >> .env
        echo "BROKER_SSL=${{ secrets.BROKER_SSL }}" >> .env
        echo "BROKER_USERNAME=${{ secrets.BROKER_USERNAME }}" >> .env
        echo "BROKER_PASSWORD=${{ secrets.BROKER_PASSWORD }}" >> .env
  
    - name: Set up Python
      run: |
        pip install -r requirements.txt
        pip install -e .
        pip install https://github.com/robotics-4-all/commlib-py/archive/devel.zip -U

    - name: Execute streamsim and tests in parallel
      run: |
        python3 stream_simulator/bin/bootstrap.py testing testinguid &
        sleep 5
        pytest tests/test_template.py
        pytest tests/test_robot_teleport.py
